# .github/workflows/ci.yml
name: CI

on:
  pull_request:
    branches: [develop, pre-release, main]
  push:
    branches: [develop, pre-release, main]

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: fmt
        run: deno fmt --check
      - name: lint
        run: deno lint
      - name: check
        run: deno check
  unit-test:
    needs: lint
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: test
        run: |
          deno test -A